version: "3"
services:
  blogdb:
    image: postgres:11.5
    volumes:
      - ./nebjblogdata:/var/lib/postgres/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test
      POSTGRES_DB: blogdb
    volumes:
      - nebjblogdata